FROM python:3.10-slim
WORKDIR /app
COPY ./artifacts/ .
RUN ls .
RUN pip install ./dist/F1DriverData-0.1-py3-none-any.whl
RUN pip install waitress
CMD ["waitress-serve", "--call", "f1_driver_data:create_app"]