FROM python:3.10-slim
WORKDIR /app
COPY ./artifacts/artifacts/dist/F1DriverData-0.1-py3-none-any.whl /app/
RUN ls /app/artifacts/
RUN pip install /app/F1DriverData-0.1-py3-none-any.whl
RUN pip install waitress

CMD ["waitress-serve", "--call", "f1_driver_data:create_app"]