FROM python:3.10-slim
WORKDIR /app
COPY ./artifacts /app/artifacts
RUN ls /app/artifacts/
RUN pip install /app/artifacts/*.whl
RUN pip install waitress

CMD ["waitress-serve", "--call", "f1_driver_data:create_app"]