openapi: 3.0.0
info:
  title: F1 Driver API
  description: API for retrieving F1 driver data
  version: '1.0'
paths:
  /driver/all:
    get:
      summary: Get a list of F1 drivers
      parameters:
        - name: category
          in: query
          schema:
            type: string
          description: The category to filter by
        - name: ranking
          in: query
          schema:
            type: string
          description: The ranking order ('top' or 'bottom')
        - name: n
          in: query
          schema:
            type: integer
          description: The number of drivers to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /driver/{driver_name}:
    get:
      summary: Get a specific F1 driver by name
      parameters:
        - name: driver_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the driver to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Driver:
      type: object
      properties:
        name:
          type: string
          description: The full name of the driver.
          example: "Lewis Hamilton"
        nationality:
          type: string
          description: The nationality of the driver.
          example: "British"
        seasons:
          type: integer
          description: The number of seasons the driver has participated in.
          example: 15
        championships:
          type: integer
          description: The number of F1 championships won by the driver.
          example: 7
        entries:
          type: integer
          description: The total number of race entries by the driver.
          example: 250
        starts:
          type: integer
          description: The total number of race starts by the driver.
          example: 250
        poles:
          type: integer
          description: The total number of pole positions achieved by the driver.
          example: 101
        wins:
          type: integer
          description: The total number of race wins by the driver.
          example: 100
        podiums:
          type: integer
          description: The total number of podium finishes by the driver.
          example: 150
